const dummyData = [
  {
    id: 0,
    thumbnail: "https://i.postimg.cc/5yPLHjxp/brand0.png",
    title: "UX/UI 디자인 리드",
    description:
      "3~5년차, photoshop, illustrator, 내용이 길어지는 다람쥐 헌 쳇바퀴에 돌고파 길어지는 다람쥐 헌 쳇바퀴에 돌고파 ",
    companyImg: "https://i.postimg.cc/X7RXs9Dd/brand-Logo0.png",
    companyName: "한국학중앙연구회",
    welfare: "자율근무제, 하프데이, 개인 법인카드",
    gradePoint: 4.0,
    gradeCount: 504,
    congratulationMoney: 200,
  },
  {
    id: 1,
    thumbnail: "https://i.postimg.cc/c4r89x1y/brand1.png",
    title: "인사담당자 채용 (사원, 대리)",
    description:
      "3~5년차, photoshop, illustrator, 내용이 길어지는 다람쥐 헌 쳇바퀴에 돌고파 길어지는 다람쥐 헌 쳇바퀴에 돌고파 ",
    companyImg: "https://i.postimg.cc/Fsd7bTGh/brand-Logo1.png",
    companyName: "헤드헌팅 공고",
    welfare: "점심 식대 지원 12,000원",
    gradePoint: 0.0,
    gradeCount: 0,
    congratulationMoney: 200,
  },
  {
    id: 2,
    thumbnail: "https://i.postimg.cc/3Nb086Bc/brand2.png",
    title: "주니어 프로덕트 디자이너",
    description:
      "3~5년차, photoshop, illustrator, 내용이 길어지는 다람쥐 헌 쳇바퀴에 돌고파 길어지는 다람쥐 헌 쳇바퀴에 돌고파 ",
    companyImg: "https://i.postimg.cc/43ZygsG3/brand-Logo2.png",
    companyName: "잡플래닛",
    welfare: "시차출퇴근제, 복지포인트",
    gradePoint: 4.2,
    gradeCount: 196,
    congratulationMoney: 200,
  },
  {
    id: 3,
    thumbnail: "https://i.postimg.cc/v8PVtgst/brand3.png",
    title: "UX/UI 디자인 리드",
    description:
      "3~5년차, photoshop, illustrator, 내용이 길어지는 다람쥐 헌 쳇바퀴에 돌고파 길어지는 다람쥐 헌 쳇바퀴에 돌고파 ",
    companyImg: "https://i.postimg.cc/tg5TRwRN/brand-Logo3.png",
    companyName: "한국학중앙연구회",
    welfare: "자율근무제, 하프데이, 개인 법인카드",
    gradePoint: 4.0,
    gradeCount: 504,
    congratulationMoney: 200,
  },
  {
    id: 4,
    thumbnail: "https://i.postimg.cc/d0m7kD6d/brand4.png",
    title: "인사담당자 채용 (사원, 대리)",
    description:
      "3~5년차, photoshop, illustrator, 내용이 길어지는 다람쥐 헌 쳇바퀴에 돌고파 길어지는 다람쥐 헌 쳇바퀴에 돌고파 ",
    companyImg: "https://i.postimg.cc/Kz8Y1fRS/brand-Logo4.png",
    companyName: "헤드헌팅 공고",
    welfare: "점심 식대 지원 12,000원",
    gradePoint: 0.0,
    gradeCount: 0,
    congratulationMoney: 200,
  },
  {
    id: 5,
    thumbnail: "https://i.postimg.cc/L8PgSxZx/brand5.png",
    title: "주니어 프로덕트 디자이너",
    description:
      "3~5년차, photoshop, illustrator, 내용이 길어지는 다람쥐 헌 쳇바퀴에 돌고파 길어지는 다람쥐 헌 쳇바퀴에 돌고파 ",
    companyImg: "https://i.postimg.cc/wv4jLNmt/brand-Logo5.png",
    companyName: "잡플래닛",
    welfare: "시차출퇴근제, 복지포인트",
    gradePoint: 4.2,
    gradeCount: 196,
    congratulationMoney: 200,
  },
  {
    id: 6,
    thumbnail: "https://i.postimg.cc/CLXn93dZ/brand6.png",
    title: "UX/UI 디자인 리드",
    description:
      "3~5년차, photoshop, illustrator, 내용이 길어지는 다람쥐 헌 쳇바퀴에 돌고파 길어지는 다람쥐 헌 쳇바퀴에 돌고파 ",
    companyImg: "https://i.postimg.cc/XqZ78vfs/brand-Logo6.png",
    companyName: "한국학중앙연구회",
    welfare: "자율근무제, 하프데이, 개인 법인카드",
    gradePoint: 4.0,
    gradeCount: 504,
    congratulationMoney: null,
  },
  {
    id: 7,
    thumbnail: "https://i.postimg.cc/yd1DFBpG/brand7.png",
    title: "인사담당자 채용 (사원, 대리)",
    description:
      "3~5년차, photoshop, illustrator, 내용이 길어지는 다람쥐 헌 쳇바퀴에 돌고파 길어지는 다람쥐 헌 쳇바퀴에 돌고파 ",
    companyImg: "https://i.postimg.cc/qq9BZdQ4/brand-Logo7.png",
    companyName: "헤드헌팅 공고",
    welfare: "점심 식대 지원 12,000원",
    gradePoint: 0.0,
    gradeCount: 0,
    congratulationMoney: null,
  },
  {
    id: 8,
    thumbnail: "https://i.postimg.cc/jjrwSyHt/brand8.png",
    title: "주니어 프로덕트 디자이너",
    description:
      "3~5년차, photoshop, illustrator, 내용이 길어지는 다람쥐 헌 쳇바퀴에 돌고파 길어지는 다람쥐 헌 쳇바퀴에 돌고파 ",
    companyImg: "https://i.postimg.cc/1315GsfK/brand-Logo8.png",
    companyName: "잡플래닛",
    welfare: "시차출퇴근제, 복지포인트",
    gradePoint: 4.2,
    gradeCount: 196,
    congratulationMoney: null,
  },
];

export default dummyData;
